# H2 Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Plants_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Database initialization and data script
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Secret Keys
secret_key="190b9aa3d0a520ab8757d16ab7e787e6fbe8cdf688b5c9dccbedbef29b09761b"
google_client_id=603295955893-878oteqf06o5rneei4m7sd1mu5ieqs9n.apps.googleusercontent.com
recaptcha.secret=6Lf5owwpAAAAAMLjCa0YAOrnKOrz9Ur37YkJiJ7E